### ISSUE TITLE
Update instructions for editing an existing archive

### ISSUE THREAD

**Issue by bvreede** [zenodraft/zenodraft#57]
In the [full CLI usage explainer](https://github.com/zenodraft/zenodraft/blob/main/README.cli-usage.md) the following code is given for editing an existing collection:

```
zenodraft deposition create in-existing-collection $CONCEPT_RECORD_ID
```
However, when editing an archive that already exists on Zenodo, the ID of the existing record is needed instead of the concept record, which was the last element of the DOI for all versions, in my case:

![image](https://user-images.githubusercontent.com/5747405/158354643-04c482bd-8281-434b-9386-a6a9eabc1f73.png)

It would be useful to have this mentioned explicitly in the documentation.

**Comment by jspaaks** [comment]
Just to clarify, you're suggesting to add a note to the documentation that explains where to get the value for `$CONCEPT_RECORD_ID` as used in the examples?

**Comment by bvreede** [comment]
This is the record ID, correct?

I think it would be useful to have that explicit in the documentation, yes, but this issue is because the documentation for `in-existing-collection` refers to the use of the `$CONCEPT_RECORD_ID`, whereas the `$RECORD_ID` is what is actually needed.

At least that is how I interpreted it! :)

**Comment by jspaaks** [comment]
> This is the record ID, correct?

What you have hightlighted in the top post is the identifier for the concept, i.e. `$CONCEPT_RECORD_ID`.

> because the documentation for in-existing-collection refers to the use of the $CONCEPT_RECORD_ID, whereas the $RECORD_ID is what is actually needed.

I don't think that's accurate though. The [documentation for `0.11.1`](https://github.com/zenodraft/zenodraft/blob/0.11.1/README.cli-usage.md) says: 

```shell
zenodraft --sandbox deposition create in-existing-collection $CONCEPT_RECORD_ID
```

That call will return a new id, which identifies the newly created record in the collection-with-identifier-`$CONCEPT_RECORD_ID`. That is, the new record is "a version of the concept", in Zenodo-speak.

Once you have the id of the new record, you can use it to upload files. As per the documentation, 

```shell
zenodraft --sandbox file add $RECORD_ID file.txt
```

See for example, your script:

1. https://github.com/bvreede/zenodo_upload/blob/main/new_zenodo_release.sh#L2 (creates new record in existing collection 5645153, captures the record id as `RECORD_ID`)
2. https://github.com/bvreede/zenodo_upload/blob/e6fe6ae0fb4191271caecc3ddbfe500437b47ef8/new_zenodo_release.sh#L15 (uses the record id to upload a local file)

I think the documentation as-is accurately represent what is needed. I you agree, I'd like to close this issue.
