### ISSUE TITLE
Validate metadata

### ISSUE THREAD

**Issue by dennisangemi** [zenodraft/zenodraft#76]
Thx for this tool! Is possible to add the abiliy to do something like
```
zenodraft metadata validate <local filename>
```

in order to validate the file `.zenodo.json` ? Idk if `<local filename>` makes sense: metadata file `MUST` be named `.zenodo.json` so we can simply run
```
zenodraft metadata validate
```

Maybe `<local filename>` could be optional

What do u think?

**Comment by jspaaks** [comment]
Hi @dennisangemi and thanks for making the issue! I think something like what you're suggesting is a great idea. I was planning on doing the validation behind the scenes on upload (using the JSONschema from sibling repo https://github.com/zenodraft/metadata-schema-zenodo), but making the validation accessible through the CLI is probably also useful. I'll leave this issue open for the time being to help me remember by the time I can work on this.

**Comment by dennisangemi** [comment]
Nice! Thank you so much @jspaaks

**Comment by jspaaks** [comment]
Done in 0.14.0, closing
